title: Você Na Programação
email: vicenters10@gmail.com
description: >-
  Criei esse blog para ajudar você a ter dicas sobre o mundo da programação.

baseurl: "/blog"
url: "https://ryuvi.github.io"

github_username: ryuvi
instagram: vi_rafinha
author: ryuvi

theme: minima

plugins:
  - jekyll-feed
